### client credentials 토큰 발급
POST {{host_url}}/api/oauth/token
Content-Type: application/json
Accept: application/json

{
  "grant_type" : "client_credentials",
  "client_id" : "{{client_credentials_client_id}}",
  "client_secret" : "{{client_credentials_client_secret}}"
}

### password grant 토큰 발급
POST {{host_url}}/api/oauth/token
Content-Type: application/json
Accept: application/json

{
  "grant_type" :"password",
  "client_id" : "{{password_grant_client_id}}",
  "client_secret" : "{{password_grant_client_secret}}",
  "username" :"{{user_email_for_token}}",
  "password" :"{{user_password_for_token}}",
  "scope" :"*"
}
